import mongoose from "mongoose";

/**
 * @module models/productVariant
 * Mongoose model for product variants.
 *
 * Includes:
 * - title: Variant title based on product title
 * - category: Product category (lens, frame, accessories, etc)
 * - attribute: Variant attributes (e.g. [color, size, material])
 * - products: Array of product IDs
 * - autoGenerated: Flag indicating if the variant is auto-generated
 */
const productVariantSchema = new Schema(
  {
    title: {
      type: String,
      required: true,
      trim: true,
    },
    category: {
      type: String,
      enum: ["lens", "frame", "accessories"],
      required: true,
    },
    attributes: [
      {
        type: String,
        required: true,
        trim: true,
        lowercase: true,
      },
    ],
    products: [
      {
        type: Schema.Types.ObjectId,
        ref: "Product",
      },
    ],
    autoGenerated: {
      type: Boolean,
      default: true,
    },
  },
  { timestamps: true },
);

export const ProductVariant = mongoose.model("ProductVariant", productVariantSchema);
